### ISSUE TITLE
missing module

### ISSUE THREAD

**Issue by Pouja** [techjacker/custom-errors#1]
Tap module is missing from the package.json, it's necessary for running tests.

How to reproduce

``` javascript
npm test
```

How to fix it

``` javascript
npm install tap --save
```

Sorry for the overkill of information for such simpel problem, it's a habit.

**Comment by techjacker** [comment]
Tap is only necessary for tests so it's in the dev dependencies, run `npm install --dev` and you'll be able to run the tests.
